### PR TITLE
Update dependencies, fix security vulnerabilities

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by mraible** [comment]
I'm guessing this fails in Travis because I changed the login redirect to remove `/implicit`. When I run it locally, everything passes. 

@brettritter-okta Is it possible to update the CI app to add `http://localhost:8080/callback` as a login redirect URI?

Related: it seems a `testenv` is necessary to run the tests. I have no `ISSUER` defined (proven by `echo $ISSUER`) and my tests pass.

**Comment by swiftone** [comment]
@mraible - We've been discussing how best to change the default redirect_uri (I personally have argued for `/login/callback` as `/callback` assumes an app has one single callback).  However, this is only the default setting - you should be able to configure any login redirect_uri you want.

**Comment by swiftone** [comment]
More likely this fails in Travis because you need to have certain permissions to run the e2e tests.  One minute and I'll bounce this PR to another running under my credentials.

**Comment by swiftone** [comment]
Shifting to https://github.com/okta/samples-js-angular/pull/88

**Pull request closed without merging**
