### PR TITLE
Add .NET Resource servers

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Review by laura-rodriguez — APPROVED** [review]

**Comment by mraible** [comment]
@laura-rodriguez Can you please merge this? I don't have permissions.

**Comment by laura-rodriguez** [comment]
@mraible it seems Travis failed. Can you please take a look? Happy to merge when it's fixed.

**Comment by mraible** [comment]
@laura-rodriguez This happens because I don't have the proper permissions or configuration for our samples repos. You have to create a new PR from a DevEx account, then it should pass. That's what @aarongranick-okta has been doing for me.

**Comment by laura-rodriguez** [comment]
@mraible it seems I don't have permissions to push on this repo. I'll ping the JS folks to help here.

**Comment by swiftone** [comment]
Closed in favor of #94 (same content, now with extra CI happiness)

**Pull request closed without merging**
