### PR TITLE
Prefer useFactory to inject oktaAuth instance

### PR DESCRIPTION
**Pull request by shuowu**

### CODE REVIEW

**Comment by mraible** [comment]
I'm curious. What problem does this solve?

**Comment by shuowu** [comment]
Some customers want to dynamically load OktaAuth configs from remote, the `useFactory` pattern opens the door for that. Also think it's not bad to add as a general usage for the sample apps.

**Comment by mraible** [comment]
Good idea! I use something similar for Ionic in OktaDev Schematics.

From https://github.com/oktadev/schematics/blob/main/src/add-auth/ionic/angular/src/app/auth/auth.module.ts:

```ts
{
  provide: APP_INITIALIZER,
  useFactory: authInitializer,
  multi: true,
  deps: [AuthConfigService]
}
```

**Review by jaredperreault-okta — APPROVED** [review]

**Comment by alisaduncan** [comment]
I have a suggestion for this instead of having to use the injector. Also, this fixes a lint error. Happy to submit a PR, just LMK.

```ts
{
      provide: OKTA_CONFIG,
      useFactory: () => ({
          oktaAuth: new OktaAuth(config.oidc),
          onAuthRequired: (o: OktaAuth, router: Router) => {
            // Redirect the user to your custom login page
            router.navigate(['/login']);
          }
      }),
      deps: [Router]
},
```

**Pull request closed without merging**
